version: "3"

# docker-compose -f ./src/bin/stack/stack-prod.yml --project-directory . up -d

# docker build --progress=plain --no-cache -f src/bin/stack/Dockerfile -t sphinx-swarm .

services:

  sphinx-cache:
    # image: sphinx-swarm
    image: sphinxlightning/sphinx-swarm:0.1.0
    container_name: sphinx-swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vol:/vol
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elements.rule=Host(`cache.sphinx.chat`)"
      - "traefik.http.services.elements.loadbalancer.server.port=8000"
      - "traefik.http.routers.elements.tls=true"
      - "traefik.http.routers.elements.tls.certresolver=myresolver"
      - "traefik.http.routers.elements.entrypoints=websecure"
    restart: on-failure
    environment: 
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
